/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import "PSListController.h"
@class PSListController;
@interface PSListContainerView : UIView 
@property (nonatomic) PSListController *delegate;
@end
